M48
; DRILL file {KiCad 9.0.7} date 2026-02-22T02:47:24+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-22T02:47:24+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X131.84Y-82.0
X142.0Y-82.0
X146.25Y-97.0
X146.25Y-104.62
T2
X152.5Y-82.5
X162.66Y-82.5
T3
X115.0Y-87.465
X115.0Y-92.545
X180.25Y-90.5
X180.25Y-95.58
M30
